In [54]:
import os
import pandas as pd
import numpy as np

In [55]:
#Importamos el dataset a utilizar
#Configuramos pandas para visualizar todas las columnas del dataframe
pd.set_option('display.max_columns', None)

#creamos un dataframe a partir de un dataset
df= pd.read_csv("datosConcatenados_completo.csv",sep=",",index_col=False)
df.head()

,Unnamed: 0,danho,ciclo,Cod.Asign,Asignatura,Cod.Car.Sec,Cod.Curso,Convocatoria,Anho,Semestre,Aprobado,Anho.Firma,Primer.Par,Segundo.Par,AOT,Primer.Rec,Segundo.Rec,Nota.Final,Tercer.Par,Asis,Cuarto.Par,4P_60,id_anony
0,0,2012,1,2402,COMBUSTION,INT9MECANI,13,1,2012,1,N,0,0,0,0,0,0,NaN,0.0,1.0,NaN,NaN,es_0
1,1,2012,1,2402,COMBUSTION,MEC9-OPT,13,1,2012,1,S,2012,11,14,8,0,0,1F-5,0.0,1.0,NaN,NaN,es_1
2,2,2012,1,2402,COMBUSTION,INT9MECANI,13,1,2012,1,S,2012,24,23,9,0,0,1F-5,0.0,1.0,NaN,NaN,es_2
3,3,2012,1,2402,COMBUSTION,MEC9-OPT,13,1,2012,1,S,2012,11,14,8,0,0,"1F-1,2F-2",0.0,1.0,NaN,NaN,es_3
4,4,2012,1,2402,COMBUSTION,MEC9-OPT,13,1,2012,1,N,0,11,4,8,0,0,NaN,0.0,1.0,NaN,NaN,es_4

In [56]:
df=df[df['Cod.Car.Sec']!='TIVAS     ']

In [57]:
df=df[df.Anho.values!=2020]

# Eliminacion de Datos Innecesarios
Previamente se demostro que la columna de 'danho'y 'Anho' contienen la misma informacion. Se eliminara una de ellas para eliminar datos redundantes. La columna 'Unnamed: 0' y 'Cod.Curso' tampoco aporta datos que sean de utilidad.

In [58]:
df=df.drop(['Unnamed: 0'],axis=1)
df=df.drop(['danho'],axis=1)
df=df.drop(['Cod.Curso'],axis=1)

In [59]:
df.head()

,ciclo,Cod.Asign,Asignatura,Cod.Car.Sec,Convocatoria,Anho,Semestre,Aprobado,Anho.Firma,Primer.Par,Segundo.Par,AOT,Primer.Rec,Segundo.Rec,Nota.Final,Tercer.Par,Asis,Cuarto.Par,4P_60,id_anony
0,1,2402,COMBUSTION,INT9MECANI,1,2012,1,N,0,0,0,0,0,0,NaN,0.0,1.0,NaN,NaN,es_0
1,1,2402,COMBUSTION,MEC9-OPT,1,2012,1,S,2012,11,14,8,0,0,1F-5,0.0,1.0,NaN,NaN,es_1
2,1,2402,COMBUSTION,INT9MECANI,1,2012,1,S,2012,24,23,9,0,0,1F-5,0.0,1.0,NaN,NaN,es_2
3,1,2402,COMBUSTION,MEC9-OPT,1,2012,1,S,2012,11,14,8,0,0,"1F-1,2F-2",0.0,1.0,NaN,NaN,es_3
4,1,2402,COMBUSTION,MEC9-OPT,1,2012,1,N,0,11,4,8,0,0,NaN,0.0,1.0,NaN,NaN,es_4

Tambien comprobaremos que columnas contienen datos no disponibles

# Relleno de datos faltantes
Es necesario comprobar que no falten datos en el dataframe. Pero de ser asi, es necesario llenar estos datos faltantes con algun dato auxiliar para poder realizar el preprocesamiento

In [60]:
#Primeramente, verificamos que columnas contienen datos faltantes.
df.isna().sum()/len(df)*100

ciclo             0.000000
Cod.Asign         0.000000
Asignatura        0.000000
Cod.Car.Sec       0.000000
Convocatoria      0.000000
Anho              0.000000
Semestre          0.000000
Aprobado          0.000000
Anho.Firma        0.000000
Primer.Par        0.000000
Segundo.Par       0.000000
AOT               0.000000
Primer.Rec        0.000000
Segundo.Rec       0.000000
Nota.Final       38.041172
Tercer.Par        0.000000
Asis              0.000000
Cuarto.Par      100.000000
4P_60           100.000000
id_anony          0.000000
dtype: float64

Como se puede apreciar, los datos para el 'Cuarto.Par', '4P_60' y 'Nota.Final' estan mayormente incompletas. Para solucionar este problema, se opta por llenar con 0 los datos faltantes.

In [61]:
df.fillna(0,inplace=True)

In [62]:
#Verificamos que ya no quedan datos faltantes
df.isna().sum()/len(df)*100

ciclo           0.0
Cod.Asign       0.0
Asignatura      0.0
Cod.Car.Sec     0.0
Convocatoria    0.0
Anho            0.0
Semestre        0.0
Aprobado        0.0
Anho.Firma      0.0
Primer.Par      0.0
Segundo.Par     0.0
AOT             0.0
Primer.Rec      0.0
Segundo.Rec     0.0
Nota.Final      0.0
Tercer.Par      0.0
Asis            0.0
Cuarto.Par      0.0
4P_60           0.0
id_anony        0.0
dtype: float64

In [63]:
df.head()

,ciclo,Cod.Asign,Asignatura,Cod.Car.Sec,Convocatoria,Anho,Semestre,Aprobado,Anho.Firma,Primer.Par,Segundo.Par,AOT,Primer.Rec,Segundo.Rec,Nota.Final,Tercer.Par,Asis,Cuarto.Par,4P_60,id_anony
0,1,2402,COMBUSTION,INT9MECANI,1,2012,1,N,0,0,0,0,0,0,0,0.0,1.0,0.0,0.0,es_0
1,1,2402,COMBUSTION,MEC9-OPT,1,2012,1,S,2012,11,14,8,0,0,1F-5,0.0,1.0,0.0,0.0,es_1
2,1,2402,COMBUSTION,INT9MECANI,1,2012,1,S,2012,24,23,9,0,0,1F-5,0.0,1.0,0.0,0.0,es_2
3,1,2402,COMBUSTION,MEC9-OPT,1,2012,1,S,2012,11,14,8,0,0,"1F-1,2F-2",0.0,1.0,0.0,0.0,es_3
4,1,2402,COMBUSTION,MEC9-OPT,1,2012,1,N,0,11,4,8,0,0,0,0.0,1.0,0.0,0.0,es_4

# Preprocesamiento de Datos
Como ya nos encargamos de los datos faltantes. Ahora es necesario procesar ciertos datos tal que la lectura para su uso sea mas accesible para el algoritmo.

Empecemos por lo mas sencillo, si el alumno aprobo o no la materia. Si bien tenemos la columna 'Aprobado' esta columna tiene como datos S y N. Es necesario cambiar esto por algo mas legible para el algoritmo

In [64]:
df["Aprobado"].replace({"S": 1, "N": 0}, inplace=True)
df.head()

,ciclo,Cod.Asign,Asignatura,Cod.Car.Sec,Convocatoria,Anho,Semestre,Aprobado,Anho.Firma,Primer.Par,Segundo.Par,AOT,Primer.Rec,Segundo.Rec,Nota.Final,Tercer.Par,Asis,Cuarto.Par,4P_60,id_anony
0,1,2402,COMBUSTION,INT9MECANI,1,2012,1,0,0,0,0,0,0,0,0,0.0,1.0,0.0,0.0,es_0
1,1,2402,COMBUSTION,MEC9-OPT,1,2012,1,1,2012,11,14,8,0,0,1F-5,0.0,1.0,0.0,0.0,es_1
2,1,2402,COMBUSTION,INT9MECANI,1,2012,1,1,2012,24,23,9,0,0,1F-5,0.0,1.0,0.0,0.0,es_2
3,1,2402,COMBUSTION,MEC9-OPT,1,2012,1,1,2012,11,14,8,0,0,"1F-1,2F-2",0.0,1.0,0.0,0.0,es_3
4,1,2402,COMBUSTION,MEC9-OPT,1,2012,1,0,0,11,4,8,0,0,0,0.0,1.0,0.0,0.0,es_4

In [65]:
#Renombramos las columnas con nombres complicados a otros mas sencillos
df.rename(columns={'ciclo' : 'Ciclo','Primer.Par':'1P','Segundo.Par':'2P','AOT':'Taller','Primer.Rec':'1R'},inplace = True)
df.rename(columns={'Segundo.Rec':'2R','Tercer.Par':'3P','Cuarto.Par':'4P','Asis':'Asistencia'},inplace = True)

df.head()

,Ciclo,Cod.Asign,Asignatura,Cod.Car.Sec,Convocatoria,Anho,Semestre,Aprobado,Anho.Firma,1P,2P,Taller,1R,2R,Nota.Final,3P,Asistencia,4P,4P_60,id_anony
0,1,2402,COMBUSTION,INT9MECANI,1,2012,1,0,0,0,0,0,0,0,0,0.0,1.0,0.0,0.0,es_0
1,1,2402,COMBUSTION,MEC9-OPT,1,2012,1,1,2012,11,14,8,0,0,1F-5,0.0,1.0,0.0,0.0,es_1
2,1,2402,COMBUSTION,INT9MECANI,1,2012,1,1,2012,24,23,9,0,0,1F-5,0.0,1.0,0.0,0.0,es_2
3,1,2402,COMBUSTION,MEC9-OPT,1,2012,1,1,2012,11,14,8,0,0,"1F-1,2F-2",0.0,1.0,0.0,0.0,es_3
4,1,2402,COMBUSTION,MEC9-OPT,1,2012,1,0,0,11,4,8,0,0,0,0.0,1.0,0.0,0.0,es_4

In [66]:
#Ahora verificamos que tipos de datos utiliza cada columna
df.dtypes

Ciclo             int64
Cod.Asign         int64
Asignatura       object
Cod.Car.Sec      object
Convocatoria      int64
Anho              int64
Semestre          int64
Aprobado          int64
Anho.Firma        int64
1P                int64
2P                int64
Taller            int64
1R                int64
2R                int64
Nota.Final       object
3P              float64
Asistencia      float64
4P              float64
4P_60           float64
id_anony         object
dtype: object

In [67]:
df['Cod.Car.Sec']=df['Cod.Car.Sec'].str.slice(0, 3)

'Cod.Car.Sec' se refiere al plan y la carrera que sigue el alumno en la facultad. Este es un dato relevante. Asi que es necesario discretizarlo para poder utilizar esto como un dato de entrada mas adelante. Tambien es necesario aplicar el mismo procedimiento con 'Asignatura'

In [68]:
#Empecemos con la carrera
#Como Cod.Car.Sec es un object, es necesario asignarle un codigo para que sea procesable

aux1=df['Cod.Car.Sec'] 
aux2=df['Asignatura']

#Creamos un vector de tipo object que contiene las carreras con las que estamos trabajando
carreras=np.unique(df['Cod.Car.Sec'])

#Aqui se categorizan las carreras y se les asigna un numero entero como su codigo
df['Cod.Car.Sec'] = pd.Categorical(df['Cod.Car.Sec'])
df['Cod.Car.Sec'] = df['Cod.Car.Sec'].cat.codes

#Guardamos en un vector los codigos de las carreras
cod_carreras=np.unique(df['Cod.Car.Sec'])

#Visualizamos el nombre de cada carrera y su codigo respectivo
#display(carreras)
#display(cod_carreras)

#Aplicamos el mismo procedimiento para la asignatura
materias=np.unique(df['Asignatura'])
df['Asignatura'] = pd.Categorical(df['Asignatura'])
df['Asignatura'] = df['Asignatura'].cat.codes


cod_materias=np.unique(df['Asignatura'])

#display(materias)
#display(cod_materias)

In [69]:
#A continuacion, creamos dos dataframes para facilitar la identificacion de las carreras y las asignaturas
#Empezamos con el identificador de la carrera
identificador_carrera=pd.DataFrame(data=carreras,index=None,columns=["Carrera"])


identificador_carrera["Codigo"]=cod_carreras

identificador_carrera

  Carrera  Codigo
0     CGF       0
1     CIV       1
2     ECA       2
3     ELE       3
4     IND       4
5     INT       5
6     MCT       6
7     MEC       7

In [70]:
#Ahora podemos guardar este dataframe para utilizarlo en los modelos
identificador_carrera.to_csv("identificador_carrera.csv",index=False)

In [71]:
#Ahora, graficamos el identificador de la asignatura
identificador_asignatura=pd.DataFrame(data=materias,index=None,columns=["Asignatura"])
identificador_asignatura["Codigo"]=cod_materias



with pd.option_context('display.max_rows', None, 'display.max_columns', None):  # more options can be specified also
    print(identificador_asignatura)

                                            Asignatura  Codigo
0               ACONDICIONADOR DE AIRE Y REFRIGERACION       0
1           ACONDICIONAMIENTO DEL AIRE Y REFRIGERACION       1
2                       ACTUADORES Y MAQ. ELECTRICAS 1       2
3                     ACTUADORES Y MAQUINAS ELECTRICAS       3
4                          ADMINISTRACION DE EMPRESAS        4
5                              ADMINISTRACION DE RR HH       5
6                          ADMINISTRACION FINANCIERA         6
7                   AERODINAMICA DE LAS CONSTRUCCIONES       7
8                                    AEROTRIANGULACION       8
9                                   AGUAS SUBTERRANEAS       9
10                  AIRE ACONDICIONADO Y REFRIGERACION      10
11                                    ALGEBRA LINEAL 1      11
12                                    ALGEBRA LINEAL 2      12
13                                          ALGORITMOS      13
14                                        ALGORITMOS 1      14
15                                        ALGORITMOS 2      15
16                                  ANALISIS DE COSTOS      16
17                                ANALISIS DE NEGOCIOS      17
18                                ANALISIS DE SISTEMAS      18
19                   ANALISIS DE SISTEMAS DE POTENCIA       19
20                                             ANTENAS      20
21        APLIC. SIG EN EL ORDENAMIENTO RURAL Y URBANO      21
22                   APLICACION DE MODELOS HIDRAULICOS      22
23               APLICACIONES SIG  EN ESTUDIOS URBANOS      23
24                         ARQUITECTURA IP CONVERGENTE      24
25                                         ASTRONOMIA       25
26                            AUTOMATIZACION Y CONTROL      26
27                                         AUTOMOTORES      27
28                                   AVALUO Y TASACION      28
29                                  AVALUO Y TASACION       29
30                                       BASE DE DATOS      30
31                                  BIOLOGIA AMBIENTAL      31
32                               CABLEADO ESTRUCTURADO      32
33                                           CALCULO 1      33
34                                           CALCULO 2      34
35                                           CALCULO 3      35
36                                           CALCULO 4      36
37                                           CALCULO 5      37
38                         CALIDAD E IMPACTO AMBIENTAL      38
39                 CAMBIO CLIMATICO PARA LA INGENIERIA      39
40                                       CARTOGRAFIA 1      40
41                                       CARTOGRAFIA 2      41
42                       CARTOGRAFIA DIGITAL APLICADA       42
43                                CENTRALES ELECTRICAS      43
44                           CIENCIA DE LOS MATERIALES      44
45              CIENCIA Y TECNOLOGIA DE LOS MATERIALES      45
46                          CIENCIAS DE LOS MATERIALES      46
47                                   CIENCIAS SOCIALES      47
48                                CIRCUITOS ELECTRICOS      48
49                                          COMBUSTION      49
50                                    COMERCIALIZACION      50
51   COMPORTAMIENTO EXPERIMENTAL DE ELEMENTOS DE H° A°      51
52                                         COMPUTACION      52
53                              COMUNICACIONES MOVILES      53
54                              COMUNICACIONES OPTICAS      54
55                                    CONSTRUCCIONES 1      55
56                                    CONSTRUCCIONES 2      56
57                                    CONSTRUCCIONES 3      57
58                                        CONTABILIDAD      58
59                             CONTABILIDAD FINANCIERA      59
60                     CONTABILIDAD Y ADM. FINANCIERA       60
61                             CONTABILIDAD Y FINANZAS      61
62                      CONTROL NUMERICO COMPUTARIZADO      62
63                               CONTROLADORES LOGICOS      63
64                                 COSTOS INDUSTRIALES      64
65   CUENCAS HIDROLOGICAS Y EL DESARROLLO TERRITORI...      65
66                           DESARROLLOS INMOBILIARIOS      66
67                                     DIBUJO MECANICO      67
68                                      DIBUJO TECNICO      68
69                                            DINAMICA      69
70                  DINAMICA DE MAQUINAS Y VIBRACIONES      70
71   DINAMICA Y CONTROL DE SISTEMAS ELECTRICO DE PO...      71
72                               DISEÑO DE GEODATABASE      72
73                      DISEÑO DE INST. INDUSTRIALES 1      73
74                      DISEÑO DE INST. INDUSTRIALES 2      74
75             DISEÑO DE INSTALACIONES P/ INDUSTRIAS 1      75
76            DISEÑO DE INSTALACIONES P/ INSDUSTRIAS 2      76
77                                   DISEÑO DE MAQUINA      77
78                           DISEÑO DE SIST. DE MANUF.      78
79                   DISEÑO DE SISTEMAS DE MANUFACTURA      79
80                                  DISEÑO ESTRUCTURAL      80
81                    DISEÑO ESTRUCTURAL DE PAVIMENTOS      81
82                              DISEÑO GEOMETRICO VIAL      82
83                               DISEÑO LOGICO DIGITAL      83
84                             DISEÑO LOGICO DIGITAL 1      84
85                             DISEÑO LOGICO DIGITAL 2      85
86                   DISEÑO Y COMPOS. DE MAPAS Y ATLAS      86
87            DISEÑO Y DESARROLLO DE PROYECTOS URBANOS      87
88          DISEÑO Y DESARROLLO DE PROYECTOS URBANOS 2      88
89             DISEÑO Y PUBLICACION DE MAPAS EN LA WEB      89
90                 DISTRIBUCION DE  ENERGIA  ELECTRICA      90
91                   DISTRIBUCION DE ENERGIA ELECTRICA      91
92                                            ECONOMIA      92
93                 ECONOMIA  Y  EVALUACION DE PROYECTO      93
94                                  ECONOMIA AMBIENTAL      94
95                                   ECONOMIA POLITICA      95
96                                  ECONOMIA POLITICA       96
97                   ECONOMIA Y EVALUACION DE PROYECTO      97
98                                          EDAFOLOGIA      98
99                                         EDAFOLOGIA       99
100                              EFICIENCIA ENERGETICA     100
101                ELECTRICIDAD Y CIRCUITOS ELECTRICOS     101
102                                  ELECTROMAGNETISMO     102
103                                ELECTROMAGNETISMO 1     103
104                                ELECTROMAGNETISMO 2     104
105                                      ELECTRONICA 1     105
106                                      ELECTRONICA 2     106
107                                      ELECTRONICA 3     107
108                 ELECTRONICA APLICADA EN POTENCIAS      108
109                                 ELECTRONICA BASICA     109
110                      ELECTRONICA BASICA INDUSTRIAL     110
111                             ELECTRONICA INDUSTRIAL     111
112                                      ELECTROTECNIA     112
113                                    ELECTROTECNIA 1     113
114                                    ELECTROTECNIA 2     114
115           ELECTROTECNIA E INSTALACIONES ELECTRICAS     115
116          ELECTROTECNIA E INSTALACIONES ELECTRICAS      116
117                              ELEMENTOS DE MAQUINAS     117
118                            ENERGIA SOLAR Y BIOMASA     118
119                                           ESTATICA     119
120              ESTRATEGIAS Y TECNICAS DE NEGOCIACION     120
121                               ESTRUCT. MET. ESPEC.     121
122                       ESTRUCTURA DE MADERA Y METAL     122
123                   ESTRUCTURA METALICA Y DE MADERAS     123
124                                      ESTRUCTURAS 1     124
125                                      ESTRUCTURAS 2     125
126                                      ESTRUCTURAS 3     126
127                              ESTRUCTURAS METALICAS     127
128                                ESTUDIOS DE SUELOS      128
129                            EVALUACION DE PROYECTOS     129
130                                  EVALUACION SOCIAL     130
131                     EVALUACION Y GESTION AMBIENTAL     131
132                    EVALUACION Y GESTION AMBIENTAL      132
133                            FENOMENOS DE TRANSPORTE     133
134                                           FINANZAS     134
135                                           FISICA 1     135
136                                           FISICA 2     136
137                                           FISICA 3     137
138                                           FISICA 4     138
139                          FISICA DE SEMICONDUCTORES     139
140                                FISICA GRAVIMETRICA     140
141                               FISICA GRAVIMETRICA      141
142                        FORM. Y EVAL. DE PROYECTOS      142
143                    FORM. Y EVALUACION DE PROYECTOS     143
144               FORMULACION Y EVALUACION DE PROYECTO     144
145                 FORMULACION Y GESTION DE PROYECTOS     145
146                                    FOTOGRAMETRIA 1     146
147                                    FOTOGRAMETRIA 2     147
148                                   FOTOGRAMETRIA 2      148
149                              FOTOGRAMETRIA DIGITAL     149
150                                    FOTOGRAMETRIA I     150
151                                  FOTONICA APLICADA     151
152                    FUNDAMENTO DE LA MECANICA NAVAL     152
153              FUNDAMENTOS DE ELECTRONICA INDUSTRIAL     153
154                        FUNDAMENTOS DE MEDIO DE RED     154
155                      FUNDAMENTOS DE PLANTA EXTERNA     155
156  FUNDAMENTOS MATEMATICOS PARA LA CIENCIAS GEOGR...     156
157                                GEODESIA GEOMETRICA     157
158                               GEODESIA GEOMETRICA      158
159                              GEODESIA GRAVIMETRICA     159
160                             GEODESIA GRAVIMETRICA      160
161                                 GEODESIA SATELITAL     161
162                                   GEOGRAFIA HUMANA     162
163                                  GEOGRAFIA HUMANA      163
164                                GEOGRAFIA TURISTICA     164
165                              GEOLOGIA DEL PARAGUAY     165
166                                   GEOLOGIA GENERAL     166
167                                  GEOLOGIA GENERAL      167
168                                GEOMETRIA ANALITICA     168
169                              GEOMETRIA DESCRIPTIVA     169
170                                      GEOMORFOLOGIA     170
171                                     GEOMORFOLOGIA      171
172                                        GEOTECNIA 1     172
173                                        GEOTECNIA 2     173
174               GEST. DE CALIDAD E IMPACTO AMBIENTAL     174
175                                 GESTION DE CALIDAD     175
176                                GESTION DE CALIDAD      176
177             GESTION DE LA CALIDAD Y MEDIO AMBIENTE     177
178                               GESTION DE PROYECTOS     178
179               GESTION DE SALUD Y SEGURIDAD INDUST.     179
180                                GESTION EMPRESARIAL     180
181                       GESTION INTEGRAL DE RESIDUOS     181
182       GESTION Y CONSERVACION DE RECURSOS NATURALES     182
183                                       HIDRAULICA 1     183
184                                       HIDRAULICA 2     184
185                                      HIDROGEOLOGIA     185
186                                       HIDROLOGIA 2     186
187                  HIDROLOGIA GENERAL  E HIDRAULICA      187
188                    HIDROLOGIA GENERAL E HIDRAULICA     188
189                                      HIDROTECNIA 1     189
190                                      HIDROTECNIA 2     190
191                     HIGIENE Y SEGURIDAD INDUSTRIAL     191
192                                  HORMIGON ARMADO 1     192
193                                  HORMIGON ARMADO 2     193
194                                HORMIGON PRETENSADO     194
195                  IMPACTO AMBIENTAL EN OBRAS VIALES     195
196                                        INFORMATICA     196
197                                      INFORMATICA 2     197
198                INFRAESTRUCTURA DE DATOS ESPECIALES     198
199        INGENIERIA DE CONFIABILIDAD Y MANTENIMIENTO     199
200                        INGENIERIA DE MANTENIMIENTO     200
201                             INGENIERIA DEL TRAFICO     201
202                               INGENIERIA ECONOMICA     202
203                                     INGLES TECNICO     203
204                                INMOTICA Y DOMOTICA     204
205           INSTALACION Y EQUIPAMIENTO DE EDIFICIOS      205
206                         INSTALACIONES  ELECTRICAS      206
207                        INSTALACIONES  INDUSTRIALES     207
208                           INSTALACIONES ELECTRICAS     208
209                INSTALACIONES ELECTRICAS ESPECIALES     209
210                         INSTALACIONES INDUSTRIALES     210
211               INSTALACIONES Y EQUIPOS DE EDIFICIOS     211
212                       INSTR. PARA CONTROL Y AUTOM.     212
213                        INSTRUMENTACION PARA TELEC.     213
214            INSTRUMENTACION PARA TELECOMUNICACIONES     214
215                   INSTRUMENTACION Y AUTOMATIZACION     215
216            INSTRUMENTACION Y MEDICIONES ELECTRICAS     216
217                   INSTRUMENTACIÓN Y AUTOMATIZACION     217
218         INSTRUMENTOS PARA CONTROL Y AUTOMATIZACION     218
219                      INT. A LA PROGRAMACION DE CNC     219
220                            INTELIGENCIA ARTIFICIAL     220
221                   INTERPRETACION DE IMAGENES RADAR     221
222  INTR AL DESARROLLO TERRITORIAL- MANEJO DE CONS...     222
223  INTR. AL PROYECTO Y DISEÑO DE TORRES DE TELECO...     223
224                      INTROD. A LA INGENIERIA NAVAL     224
225                   INTRODUCCION  A LA INVESTIGACION     225
226                  INTRODUCCION A ELECTRONICA MEDICA     226
227                INTRODUCCION A LA CIENCIA AMBIENTAL     227
228               INTRODUCCION A LA ELECTRONICA MEDICA     228
229                   INTRODUCCION A LA ENERGIA EOLICA     229
230             INTRODUCCION A LA ENERGIA FOTOVOLTAICA     230
231       INTRODUCCION A LA FISICA ATOMICA Y MOLECULAR     231
232               INTRODUCCION A LA GESTION DE ACTIVOS     232
233                    INTRODUCCION A LA INVESTIGACION     233
234                          INTRODUCCION A LA MINERIA     234
235                       INTRODUCCION A LA SIMULACION     235
236          INTRODUCCION AL ORDENAMIENTO TERRITORIAL      236
237                           INVEST. DE OPERACIONES 2     237
238                           INVEST. DE OPERACIONES 3     238
239                     INVESTIGACION DE OPERACIONES 1     239
240                     INVESTIGACION DE OPERACIONES 2     240
241                     INVESTIGACION DE OPERACIONES 3     241
242                            INVESTIGACION OPERATIVA     242
243                               LABORATORIO DE REDES     243
244                             LABORATORIO MECANICO 1     244
245                             LABORATORIO MECANICO 2     245
246                             LABORATORIO MECANICO 3     246
247                                   LABORATORIO VIAL     247
248                                    LEAN PRODUCTION     248
249                                        LEGISLACION     249
250                           LENGUAJE DE PROGRAMACION     250
251                    LENGUAJE DE PROGRAMACION VISUAL     251
252      LEVANT. REG., CATASTRALES E HIDROTOPOGRAFICOS     252
253            LEVANTAMIENTO REGIONALES Y CATASTRALES      253
254                                          LOGISTICA     254
255                         LT PARA TELECOMUNICACIONES     255
256                           MANTENIMIENTO DE CAMINOS     256
257                           MANTENIMIENTO INDUSTRIAL     257
258                             MANTENIMIENTO MECANICO     258
259                            MAQUINAS  ELECTRICAS  1     259
260                              MAQUINAS  TERMICAS  2     260
261                                  MAQUINAS DE FLUJO     261
262                                 MAQUINAS DE FLUJO      262
263                                MAQUINAS ELECTRICAS     263
264                              MAQUINAS ELECTRICAS 1     264
265                              MAQUINAS ELECTRICAS 2     265
266                               MAQUINAS HIDRAULICAS     266
267                               MAQUINAS TERMICAS  1     267
268                                MAQUINAS TERMICAS 1     268
269                                MAQUINAS TERMICAS 2     269
270            MAQUINAS Y EQUIPOS PARA LA CONSTRUCCION     270
271                                       MATERIALES 1     271
272                                       MATERIALES 2     272
273                           MATERIALES DE INGENIERIA     273
274                       MATERIALES DE OBRAS CIVILES      274
275                      MATERIALES DE OBRAS CIVILES 1     275
276                      MATERIALES DE OBRAS CIVILES 2     276
277                                MECANICA DE FLUIDOS     277
278                     MECANICA DE FLUIDOS AVANZADOS      278
279                           MECANICA DE MATERIALES 1     279
280                           MECANICA DE MATERIALES 2     280
281                                MECANICA DE SOLIDOS     281
282                           MECANICA DE SUELO Y ROCA     282
283                                         MECANISMOS     283
284                            MECANIZADO CONVENCIONAL     284
285                         MEDICION E INSTRUMENTACION     285
286                       MEDICIONES E INSTRUMENTACION     286
287                                MERCADOS ELECTRICOS     287
288                        METEOROLOGIA Y CLIMATOLOGIA     288
289                       METODOLOGIA DE INVESTIGACION     289
290                   METODOLOGIA DE LA INVESTIGACION      290
291                                  METODOS NUMERICOS     291
292                                         METROLOGIA     292
293                                 MICROCONTROLADORES     293
294                                   MICROELECTRONICA     294
295                                         MICROONDAS     295
296                                MONITOREO AMBIENTAL     296
297                       MOTORES Y COMPONENTES AUTOM.     297
298                                NOCIONES DE DERECHO     298
299                                    OBRAS FLUVIALES     299
300                                   OBRAS FLUVIALES      300
301                           OPERACIONES INDUSTRIALES     301
302                           ORGANIZACION DE EMPRESAS     302
303                         ORGANIZACION DE EMPRESAS 1     303
304                         ORGANIZACION DE EMPRESAS 2     304
305                            ORGANIZACION INDUSTRIAL     305
306    ORGANIZACION INDUSTRIAL Y SEGURIDAD DEL TRABAJO     306
307                                           PASANTIA     307
308                                          PASANTIAS     308
309                                         PASANTIAS      309
310          PATOLOGIA Y TERAPIA DE LAS CONSTRUCCIONES     310
311               PLANEAMIENTO Y CONTROL DE PRODUCCION     311
312                 PLANIF. Y CONTROL DE LA PRODUCCION     312
313               PLANIFICACION DE SISTEMAS ELECTRICOS     313
314                 PLANIFICACION DEL USO DE LA TIERRA     314
315  PLANIFICACION ESTRATEGICA PARA EL PROYECTO TER...     315

In [72]:
#Ahora podemos guardar este dataframe para utilizarlo en los modelos
identificador_asignatura.to_csv("identificador_asignatura.csv",index=False)

In [73]:
#Visualizamos los tipos de datos con los que trabajamos ahora
display(df.dtypes)
#Visualizamos el modelo
df.head()

Ciclo             int64
Cod.Asign         int64
Asignatura        int16
Cod.Car.Sec        int8
Convocatoria      int64
Anho              int64
Semestre          int64
Aprobado          int64
Anho.Firma        int64
1P                int64
2P                int64
Taller            int64
1R                int64
2R                int64
Nota.Final       object
3P              float64
Asistencia      float64
4P              float64
4P_60           float64
id_anony         object
dtype: object

,Ciclo,Cod.Asign,Asignatura,Cod.Car.Sec,Convocatoria,Anho,Semestre,Aprobado,Anho.Firma,1P,2P,Taller,1R,2R,Nota.Final,3P,Asistencia,4P,4P_60,id_anony
0,1,2402,49,5,1,2012,1,0,0,0,0,0,0,0,0,0.0,1.0,0.0,0.0,es_0
1,1,2402,49,7,1,2012,1,1,2012,11,14,8,0,0,1F-5,0.0,1.0,0.0,0.0,es_1
2,1,2402,49,5,1,2012,1,1,2012,24,23,9,0,0,1F-5,0.0,1.0,0.0,0.0,es_2
3,1,2402,49,7,1,2012,1,1,2012,11,14,8,0,0,"1F-1,2F-2",0.0,1.0,0.0,0.0,es_3
4,1,2402,49,7,1,2012,1,0,0,11,4,8,0,0,0,0.0,1.0,0.0,0.0,es_4

Tambien vamos a anotar si el alumno es recursante. Eso se puede saber a partir de la columna "Anho.Firma"

In [74]:
#Creamos un vector que confirma si un alumno es recursante
recursante=df['Anho.Firma']!=0
recursante
#Pasamos los datos booleanos del vector a formato entero
recursante=recursante.replace([True,False],[1,0])
#Este dato sera anhadido al dataframe mas adelante

Ahora es necesario procesar los datos que se encuentran en la nota final. Actualmente, la columna 'Nota.Final' es un objeto. Se optara por obtener el puntaje que el alumno adquirio en cada examen final y finalmente se anhadira una columna con el puntaje final adquirido en esa materia

In [75]:
#Primero comprobamos que tipos de datos hay en la columnas de 'Nota.Final'. Con esta informacion, sera mas sencillo definir
#el algoritmo para extraer las notas finales
notas=np.unique(df['Nota.Final'].tolist())
print(notas)

['0' '1F-1' '1F-1,2F-1' '1F-1,2F-1,3F-1' '1F-1,2F-1,3F-2' '1F-1,2F-1,3F-3'
 '1F-1,2F-1,3F-4' '1F-1,2F-1,3F-5' '1F-1,2F-1,ME-3' '1F-1,2F-2'
 '1F-1,2F-3' '1F-1,2F-4' '1F-1,2F-5' '1F-1,2F-C-2' '1F-1,2F-C-4'
 '1F-1,3F-1' '1F-1,3F-1,2F-1' '1F-1,3F-2' '1F-1,3F-2,2F-1' '1F-1,3F-3'
 '1F-1,3F-3,2F-1' '1F-1,3F-4' '1F-1,3F-4,2F-1' '1F-1,3F-5'
 '1F-1,3F-5,2F-1' '1F-1,3F-C-1' '1F-1,3F-C-3' '1F-1,ME-3' '1F-2' '1F-3'
 '1F-4' '1F-5' '1F-5F' '1F-C-1' '1F-C-1,2F-C-1' '1F-C-1,2F-C-1,3F-C-1'
 '1F-C-1,2F-C-1,3F-C-2' '1F-C-1,2F-C-1,3F-C-3' '1F-C-1,2F-C-1,3F-C-4'
 '1F-C-1,2F-C-1,3F-C-5' '1F-C-1,2F-C-2' '1F-C-1,2F-C-3' '1F-C-1,2F-C-4'
 '1F-C-1,2F-C-5' '1F-C-1,3F-C-1' '1F-C-1,3F-C-1,2F-C-1' '1F-C-1,3F-C-2'
 '1F-C-1,3F-C-2,2F-C-1' '1F-C-1,3F-C-3' '1F-C-1,3F-C-3,2F-C-1'
 '1F-C-1,3F-C-4' '1F-C-1,3F-C-4,2F-C-1' '1F-C-1,3F-C-5' '1F-C-2' '1F-C-3'
 '1F-C-4' '1F-C-5' '1F-C-5F' '1F-D-1,2F-2' '1F-D-1,2F-C-3' '1F-D-1,2F-C-4'
 '1F-D-1,3F-1' '1F-D-2' '1F-D-4' '1F-D-5' '2F-1' '2F-1,1F-1'
 '2F-1,1F-1,3F-1' '2F-1,1F-1,3F-2' '2F-1,1F-1,3F-3' '2F-1,1F-1,3F-4'
 '2F-1,1F-1,3F-5' '2F-1,3F-1' '2F-1,3F-2' '2F-1,3F-3' '2F-1,3F-3,1F-1'
 '2F-1,3F-4' '2F-1,3F-5' '2F-1,3F-C-1' '2F-2' '2F-2,1F-1' '2F-3'
 '2F-3,1F-1' '2F-4' '2F-4,1F-1' '2F-5' '2F-5,1F-1' '2F-5F' '2F-C-1'
 '2F-C-1,1F-C-1' '2F-C-1,1F-C-1,3F-C-1' '2F-C-1,1F-C-1,3F-C-2'
 '2F-C-1,1F-C-1,3F-C-3' '2F-C-1,1F-C-1,3F-C-4' '2F-C-1,3F-C-1'
 '2F-C-1,3F-C-2' '2F-C-1,3F-C-3' '2F-C-1,3F-C-4' '2F-C-1,3F-C-5' '2F-C-2'
 '2F-C-2,1F-C-1' '2F-C-3' '2F-C-3,1F-C-1' '2F-C-4' '2F-C-4,1F-C-1'
 '2F-C-5' '2F-C-5,1F-C-1' '3F-1' '3F-1,1F-1' '3F-1,1F-1,2F-1' '3F-1,2F-1'
 '3F-2' '3F-2,1F-1' '3F-2,1F-1,2F-1' '3F-2,2F-1' '3F-2,2F-1,1F-1' '3F-3'
 '3F-3,1F-1' '3F-3,1F-1,2F-1' '3F-3,2F-1' '3F-3,2F-1,1F-1' '3F-4'
 '3F-4,1F-1' '3F-4,1F-1,2F-1' '3F-4,2F-1' '3F-5' '3F-5,1F-1' '3F-5,2F-1'
 '3F-5F' '3F-C-1' '3F-C-1,1F-C-1' '3F-C-1,1F-C-1,2F-C-1' '3F-C-1,2F-C-1'
 '3F-C-2' '3F-C-2,1F-C-1' '3F-C-2,1F-C-1,2F-C-1' '3F-C-2,2F-C-1'
 '3F-C-2,2F-C-1,1F-C-1' '3F-C-3' '3F-C-3,1F-C-1' '3F-C-3,2F-C-1' '3F-C-4'
 '3F-C-4,1F-C-1' '3F-C-4,2F-C-1' '3F-C-5' '3F-C-5,2F-C-1' 'ME-2' 'ME-5']

In [76]:
#Aqui definimos la funcion que separara los datos
primerfinal=[]
segundofinal=[]
tercerfinal=[]

#Esta funcion identifica si el alumno rindio el primer, segundo o tercer final teniendo en cuenta que los finales rendidos se
#representan con 1F,2F o 3F

def separar(lista):
    global primerfinal
    global segundofinal
    global tercerfinal
    for nota in lista:
        if nota==0:
            primerfinal.append(0)
            segundofinal.append(0)
            tercerfinal.append(0)
        else:
            if '1F' in nota:
                n=nota.find('1F')
                if nota[n+3]=='C' or nota[n+3]=='D':
                    primerfinal.append(int(nota[n+5]))
                else:
                    primerfinal.append(int(nota[n+3]))
            else: 
                primerfinal.append(0)
                
            if '2F' in nota:
                n=nota.find('2F')
                if nota[n+3]=='C' or nota[n+3]=='D':
                    segundofinal.append(int(nota[n+5]))
                else:
                    segundofinal.append(int(nota[n+3]))
            else: 
                segundofinal.append(0)
            
            if '3F' in nota:
                n=nota.find('3F')
                if nota[n+3]=='C' or nota[n+3]=='D':
                    tercerfinal.append(int(nota[n+5]))
                else:
                    tercerfinal.append(int(nota[n+3]))
            else: 
                tercerfinal.append(0)

def maximo(a,b,c):
    """
    Esta funcion obtiene la nota mas alta obtenida por el alumno durante los finales. Esta funcion se 
    utiliza para obtener la nota final
    """
    salida=np.zeros(len(a))
    for i in range(len(a)):
        if a[i]>=b[i] and a[i]>=c[i]:
            salida[i]=int(a[i])
        elif b[i]>=c[i]:
            salida[i]=int(b[i])
        else:
            salida[i]=int(c[i])
    return salida.astype(np.int64)

#Cargamos el contenido de 'Nota.Final' en una lista, para asi introducir la lista en la funcion
listaNotas=df["Nota.Final"].tolist()
separar(listaNotas)

#Creamos nuevas columnas en el df y le cargamos los vectores con los datos
df['1F']=primerfinal
df['2F']=segundofinal
df['3F']=tercerfinal

#Hallamos la nota final y la cargamos en una nueva columna en el df
nota_final=maximo(primerfinal,segundofinal,tercerfinal)
df['Nota_Final']=nota_final

df.head()

,Ciclo,Cod.Asign,Asignatura,Cod.Car.Sec,Convocatoria,Anho,Semestre,Aprobado,Anho.Firma,1P,2P,Taller,1R,2R,Nota.Final,3P,Asistencia,4P,4P_60,id_anony,1F,2F,3F,Nota_Final
0,1,2402,49,5,1,2012,1,0,0,0,0,0,0,0,0,0.0,1.0,0.0,0.0,es_0,0,0,0,0
1,1,2402,49,7,1,2012,1,1,2012,11,14,8,0,0,1F-5,0.0,1.0,0.0,0.0,es_1,5,0,0,5
2,1,2402,49,5,1,2012,1,1,2012,24,23,9,0,0,1F-5,0.0,1.0,0.0,0.0,es_2,5,0,0,5
3,1,2402,49,7,1,2012,1,1,2012,11,14,8,0,0,"1F-1,2F-2",0.0,1.0,0.0,0.0,es_3,1,2,0,2
4,1,2402,49,7,1,2012,1,0,0,11,4,8,0,0,0,0.0,1.0,0.0,0.0,es_4,0,0,0,0

In [77]:
#Comprobamos nuevamente el tipo de datos en el dataframe
df.dtypes

Ciclo             int64
Cod.Asign         int64
Asignatura        int16
Cod.Car.Sec        int8
Convocatoria      int64
Anho              int64
Semestre          int64
Aprobado          int64
Anho.Firma        int64
1P                int64
2P                int64
Taller            int64
1R                int64
2R                int64
Nota.Final       object
3P              float64
Asistencia      float64
4P              float64
4P_60           float64
id_anony         object
1F                int64
2F                int64
3F                int64
Nota_Final        int64
dtype: object

Teniendo en cuenta que ya obtuvimos los puntajes de cada final y los separamos, discretizamos para su uso a los datos que pueden ser relevantes para el analisis, y convertimos los datos a un valor legible por el algoritmo. Lo que queda por hacer es eliminar las columnas a las cuales les extrajimos los datos y ya no seran relevantes para nuestro analisis. Tambien reordenamos las columnas para facilitar la lectura de los datos

In [78]:
#Primero eliminamos las columnas que ya no vamos a utilizar
df.drop(['Nota.Final', 'Convocatoria'],axis=1)

df.rename(columns={'Asignatura':'a', 'Cod.Car.Sec':'Cod.Car.Sec Codificado'},inplace = True)


df['Cod.Car.Sec']=aux1
df['Asignatura']=aux2

#Ahora reordenamos las columnas de nuestro df
df=df[['id_anony','Anho','Ciclo','Cod.Asign','Asignatura','Asignatura Codificada','Semestre','Cod.Car.Sec','Cod.Car.Sec Codificado','Anho.Firma','1P','2P','3P','4P','Taller','Asistencia','4P_60','1R','2R','1F','2F','3F','Nota_Final','Aprobado']]

#Finalmente, anhadimos la columna que indica si el alumno recurso o no la materia
df.insert(10,"Recursante",recursante,True)

In [79]:
df

,id_anony,Anho,Ciclo,Cod.Asign,Asignatura,Asignatura Codificada,Semestre,Cod.Car.Sec,Cod.Car.Sec Codificado,Anho.Firma,Recursante,1P,2P,3P,4P,Taller,Asistencia,4P_60,1R,2R,1F,2F,3F,Nota_Final,Aprobado
0,es_0,2012,1,2402,COMBUSTION,49,1,INT,5,0,0,0,0,0.0,0.0,0,1.0,0.0,0,0,0,0,0,0,0
1,es_1,2012,1,2402,COMBUSTION,49,1,MEC,7,2012,1,11,14,0.0,0.0,8,1.0,0.0,0,0,5,0,0,5,1
2,es_2,2012,1,2402,COMBUSTION,49,1,INT,5,2012,1,24,23,0.0,0.0,9,1.0,0.0,0,0,5,0,0,5,1
3,es_3,2012,1,2402,COMBUSTION,49,1,MEC,7,2012,1,11,14,0.0,0.0,8,1.0,0.0,0,0,1,2,0,2,1
4,es_4,2012,1,2402,COMBUSTION,49,1,MEC,7,0,0,11,4,0.0,0.0,8,1.0,0.0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
221916,es_4501,2021,1,5746,PROCESOS DE FABRICACION,332,1,MCT,6,0,0,0,0,0.0,0.0,0,1.0,0.0,0,0,0,0,0,0,0
221917,es_3417,2021,1,5746,PROCESOS DE FABRICACION,332,1,MCT,6,2021,1,17,26,0.0,0.0,10,1.0,0.0,0,0,0,0,0,0,0
221918,es_3784,2021,1,5746,PROCESOS DE FABRICACION,332,1,MCT,6,2021,1,19,26,0.0,0.0,10,1.0,0.0,0,0,5,0,0,5,1
221919,es_4309,2021,1,5746,PROCESOS DE FABRICACION,332,1,MCT,6,0,0,0,0,0.0,0.0,0,1.0,0.0,0,0,0,0,0,0,0
221920,es_3891,2021,1,5746,PROCESOS DE FABRICACION,332,1,MCT,6,0,0,0,0,0.0,0.0,0,1.0,0.0,0,0,0,0,0,0,0

Como los resultados de cada estudiante estan mezclados con los otros, ordenamos el dataframe de acuerdo al ID del estudiante

In [80]:
df.sort_values("id_anony",ascending=True)

df.head()

,id_anony,Anho,Ciclo,Cod.Asign,Asignatura,Asignatura Codificada,Semestre,Cod.Car.Sec,Cod.Car.Sec Codificado,Anho.Firma,Recursante,1P,2P,3P,4P,Taller,Asistencia,4P_60,1R,2R,1F,2F,3F,Nota_Final,Aprobado
0,es_0,2012,1,2402,COMBUSTION,49,1,INT,5,0,0,0,0,0.0,0.0,0,1.0,0.0,0,0,0,0,0,0,0
1,es_1,2012,1,2402,COMBUSTION,49,1,MEC,7,2012,1,11,14,0.0,0.0,8,1.0,0.0,0,0,5,0,0,5,1
2,es_2,2012,1,2402,COMBUSTION,49,1,INT,5,2012,1,24,23,0.0,0.0,9,1.0,0.0,0,0,5,0,0,5,1
3,es_3,2012,1,2402,COMBUSTION,49,1,MEC,7,2012,1,11,14,0.0,0.0,8,1.0,0.0,0,0,1,2,0,2,1
4,es_4,2012,1,2402,COMBUSTION,49,1,MEC,7,0,0,11,4,0.0,0.0,8,1.0,0.0,0,0,0,0,0,0,0

In [81]:
#Ahora modificamos el 'id_anony' por una lista de enteros, pues eso sera mas amigable para realizar procesamientos mas adelante
df["id_anony"].astype(str)
alumnos=(df["id_anony"])

alumnos= [s.replace("es_", "") for s in alumnos]

df["id_anony"]=alumnos

df["id_anony"]=df["id_anony"].astype(int)

#Tambien modificamos a tipo entero los flotantes innecesarios
df["3P"]=df["3P"].astype(int)
df["4P"]=df["4P"].astype(int)
df["Asistencia"]=df["Asistencia"].astype(int)
df["4P_60"]=df["4P_60"].astype(int)

#Ademas, se cambiaran los objetos por strings
df["Asignatura"]=df["Asignatura"].astype(str)
df["Cod.Car.Sec"]=df["Cod.Car.Sec"].astype(str)
print(df.dtypes)

id_anony                   int32
Anho                       int64
Ciclo                      int64
Cod.Asign                  int64
Asignatura                object
Asignatura Codificada      int16
Semestre                   int64
Cod.Car.Sec               object
Cod.Car.Sec Codificado      int8
Anho.Firma                 int64
Recursante                 int64
1P                         int64
2P                         int64
3P                         int32
4P                         int32
Taller                     int64
Asistencia                 int32
4P_60                      int32
1R                         int64
2R                         int64
1F                         int64
2F                         int64
3F                         int64
Nota_Final                 int64
Aprobado                   int64
dtype: object

In [82]:
df.head()

,id_anony,Anho,Ciclo,Cod.Asign,Asignatura,Asignatura Codificada,Semestre,Cod.Car.Sec,Cod.Car.Sec Codificado,Anho.Firma,Recursante,1P,2P,3P,4P,Taller,Asistencia,4P_60,1R,2R,1F,2F,3F,Nota_Final,Aprobado
0,0,2012,1,2402,COMBUSTION,49,1,INT,5,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
1,1,2012,1,2402,COMBUSTION,49,1,MEC,7,2012,1,11,14,0,0,8,1,0,0,0,5,0,0,5,1
2,2,2012,1,2402,COMBUSTION,49,1,INT,5,2012,1,24,23,0,0,9,1,0,0,0,5,0,0,5,1
3,3,2012,1,2402,COMBUSTION,49,1,MEC,7,2012,1,11,14,0,0,8,1,0,0,0,1,2,0,2,1
4,4,2012,1,2402,COMBUSTION,49,1,MEC,7,0,0,11,4,0,0,8,1,0,0,0,0,0,0,0,0

Una vez finalizado el preprocesamiento, podemos crear un nuevo dataset con las modificaciones realizadas

In [83]:
df.shape

(191390, 25)

In [84]:
#Creacion de un nuevo dataset con el dataframe final
df.to_csv("Filtrado_final.csv",index=False)