In [1]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
lectura= pd.read_csv("datos\datosConcatenados.csv")

In [3]:
lectura.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 221822 entries, 0 to 221821
Data columns (total 23 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Unnamed: 0    221822 non-null  int64
 1   danho         221822 non-null  int64
 2   ciclo         221822 non-null  int64
 3   Cod.Asign     221822 non-null  int64
 4   Asignatura    221822 non-null  object
 5   Cod.Car.Sec   221822 non-null  object
 6   Cod.Curso     221822 non-null  int64
 7   Convocatoria  221822 non-null  int64
 8   Anho          221822 non-null  int64
 9   Semestre      221822 non-null  int64
 10  Aprobado      221822 non-null  object
 11  Anho.Firma    221822 non-null  int64
 12  Primer.Par    221822 non-null  int64
 13  Segundo.Par   221822 non-null  int64
 14  AOT           221822 non-null  int64
 15  Primer.Rec    221822 non-null  int64
 16  Segundo.Rec   221822 non-null  int64
 17  Nota.Final    137062 non-null  object
 18  Tercer.Par    221822 non-null  float64
 19  Asis          221822 non-null  float64
 20  Cuarto.Par    28037 non-null   float64
 21  4P_60         28037 non-null   float64
 22  id_anony      221822 non-null  object
dtypes: float64(4), int64(14), object(5)
memory usage: 38.9+ MB

In [5]:
flag=lectura["Asignatura"]=="CALCULO 1"

0         False
1         False
2         False
3         False
4         False
          ...
221817    False
221818    False
221819    False
221820    False
221821    False
Name: Asignatura, Length: 221822, dtype: bool

In [5]:
np.unique(lectura["Cod.Car.Sec"])

array(['CGF-175-09', 'CGF-PLS09 ', 'CGF-PLS13 ', 'CIV-175-09',
       'CIV-PLS09 ', 'CIV-PLS13 ', 'ECA-175-09', 'ECA-PLS09 ',
       'ECA-PLS13 ', 'ECA9-OPT  ', 'ELE-175-09', 'ELE-PLS09 ',
       'ELE-PLS13 ', 'IND-175-09', 'IND-PLS09 ', 'IND-PLS13 ',
       'INT9-PROYT', 'INT9CONSTR', 'INT9ELECTR', 'INT9G-ECO ',
       'INT9MECANI', 'INT9ORTERR', 'INT9RNYMA ', 'INT9SANEHI',
       'INT9SDIGYT', 'INT9TRANSP', 'MCT-175-09', 'MCT-PLS09 ',
       'MCT-PLS13 ', 'MCT9-OPT  ', 'MEC-175-09', 'MEC-PLS09 ',
       'MEC-PLS13 ', 'MEC9-OPT  ', 'TIVAS     '], dtype=object)

In [12]:
#np.unique(lectura["Asignatura"])

In [27]:
lectura2 = lectura.replace("  ", " ")
lectura2["Asignatura"] = lectura2["Asignatura"].str.strip()
np.unique(lectura2["Asignatura"])

array(['ACONDICIONADOR DE AIRE Y REFRIGERACION',
       'ACONDICIONAMIENTO DEL AIRE Y REFRIGERACION',
       'ACTUADORES Y MAQ. ELECTRICAS 1',
       'ACTUADORES Y MAQUINAS ELECTRICAS', 'ADMINISTRACION DE EMPRESAS',
       'ADMINISTRACION DE RR HH', 'ADMINISTRACION FINANCIERA',
       'AERODINAMICA DE LAS CONSTRUCCIONES', 'AEROTRIANGULACION',
       'AGUAS SUBTERRANEAS', 'AIRE ACONDICIONADO Y REFRIGERACION',
       'ALGEBRA LINEAL 1', 'ALGEBRA LINEAL 2', 'ALGORITMOS',
       'ALGORITMOS 1', 'ALGORITMOS 2', 'ANALISIS DE COSTOS',
       'ANALISIS DE NEGOCIOS', 'ANALISIS DE SISTEMAS',
       'ANALISIS DE SISTEMAS DE POTENCIA', 'ANTENAS',
       'APLIC. SIG EN EL ORDENAMIENTO RURAL Y URBANO',
       'APLICACION DE MODELOS HIDRAULICOS',
       'APLICACIONES SIG  EN ESTUDIOS URBANOS',
       'ARQUITECTURA IP CONVERGENTE', 'ASTRONOMIA',
       'AUTOMATIZACION Y CONTROL', 'AUTOMOTORES', 'AVALUO Y TASACION',
       'BASE DE DATOS', 'BIOLOGIA AMBIENTAL', 'CABLEADO ESTRUCTURADO',
       'CALCULO 1', 'CALCULO 2', 'CALCULO 3', 'CALCULO 4', 'CALCULO 5',
       'CALIDAD E IMPACTO AMBIENTAL',
       'CAMBIO CLIMATICO PARA LA INGENIERIA', 'CARTOGRAFIA 1',
       'CARTOGRAFIA 2', 'CARTOGRAFIA DIGITAL APLICADA',
       'CENTRALES ELECTRICAS', 'CIENCIA DE LOS MATERIALES',
       'CIENCIA Y TECNOLOGIA DE LOS MATERIALES',
       'CIENCIAS DE LOS MATERIALES', 'CIENCIAS SOCIALES',
       'CIRCUITOS ELECTRICOS', 'COMBUSTION', 'COMERCIALIZACION',
       'COMPORTAMIENTO EXPERIMENTAL DE ELEMENTOS DE H° A°', 'COMPUTACION',
       'COMUNICACIONES MOVILES', 'COMUNICACIONES OPTICAS',
       'CONSTRUCCIONES 1', 'CONSTRUCCIONES 2', 'CONSTRUCCIONES 3',
       'CONSTRUCCIONES SOSTENIBLES', 'CONTABILIDAD',
       'CONTABILIDAD FINANCIERA', 'CONTABILIDAD Y ADM. FINANCIERA',
       'CONTABILIDAD Y FINANZAS', 'CONTROL NUMERICO COMPUTARIZADO',
       'CONTROLADORES LOGICOS', 'COSTOS INDUSTRIALES',
       'CUENCAS HIDROLOGICAS Y EL DESARROLLO TERRITORIAL PARA LA GES',
       'DESARROLLOS INMOBILIARIOS', 'DIBUJO MECANICO', 'DIBUJO TECNICO',
       'DINAMICA', 'DINAMICA DE MAQUINAS Y VIBRACIONES',
       'DINAMICA Y CONTROL DE SISTEMAS ELECTRICO DE POTENCIA',
       'DISEÑO DE GEODATABASE', 'DISEÑO DE INST. INDUSTRIALES 1',
       'DISEÑO DE INST. INDUSTRIALES 2',
       'DISEÑO DE INSTALACIONES P/ INDUSTRIAS 1',
       'DISEÑO DE INSTALACIONES P/ INSDUSTRIAS 2', 'DISEÑO DE MAQUINA',
       'DISEÑO DE SIST. DE MANUF.', 'DISEÑO DE SISTEMAS DE MANUFACTURA',
       'DISEÑO ESTRUCTURAL', 'DISEÑO ESTRUCTURAL DE PAVIMENTOS',
       'DISEÑO GEOMETRICO VIAL', 'DISEÑO LOGICO DIGITAL',
       'DISEÑO LOGICO DIGITAL 1', 'DISEÑO LOGICO DIGITAL 2',
       'DISEÑO Y COMPOS. DE MAPAS Y ATLAS',
       'DISEÑO Y DESARROLLO DE PROYECTOS URBANOS',
       'DISEÑO Y DESARROLLO DE PROYECTOS URBANOS 2',
       'DISEÑO Y PUBLICACION DE MAPAS EN LA WEB',
       'DISTRIBUCION DE  ENERGIA  ELECTRICA',
       'DISTRIBUCION DE ENERGIA ELECTRICA', 'DOMOTICA', 'ECONOMIA',
       'ECONOMIA  Y  EVALUACION DE PROYECTO', 'ECONOMIA AMBIENTAL',
       'ECONOMIA POLITICA', 'ECONOMIA Y EVALUACION DE PROYECTO',
       'EDAFOLOGIA', 'EFICIENCIA ENERGETICA',
       'ELECTRICIDAD Y CIRCUITOS ELECTRICOS', 'ELECTROMAGNETISMO',
       'ELECTROMAGNETISMO 1', 'ELECTROMAGNETISMO 2', 'ELECTRONICA 1',
       'ELECTRONICA 2', 'ELECTRONICA 3',
       'ELECTRONICA APLICADA EN POTENCIAS', 'ELECTRONICA BASICA',
       'ELECTRONICA BASICA INDUSTRIAL', 'ELECTRONICA INDUSTRIAL',
       'ELECTROTECNIA', 'ELECTROTECNIA 1', 'ELECTROTECNIA 2',
       'ELECTROTECNIA E INSTALACIONES ELECTRICAS',
       'ELEMENTOS DE MAQUINAS', 'ENERGIA SOLAR Y BIOMASA', 'ESTATICA',
       'ESTRATEGIAS Y TECNICAS DE NEGOCIACION', 'ESTRUCT. MET. ESPEC.',
       'ESTRUCTURA DE MADERA Y METAL', 'ESTRUCTURA METALICA Y DE MADERAS',
       'ESTRUCTURAS 1', 'ESTRUCTURAS 2', 'ESTRUCTURAS 3',
       'ESTRUCTURAS METALICAS', 'ESTUDIOS DE SUELOS',
       'EVALUACION DE PROYECTOS', 'EVALUACION SOCIAL',
       'EVALUACION Y GESTION AMBIENTAL', 'FENOMENOS DE TRANSPORTE',
       'FINANZAS', 'FISICA 1', 'FISICA 2', 'FISICA 3', 'FISICA 4',
       'FISICA DE SEMICONDUCTORES', 'FISICA GRAVIMETRICA',
       'FORM. Y EVAL. DE PROYECTOS', 'FORM. Y EVALUACION DE PROYECTOS',
       'FORMULACION Y EVALUACION DE PROYECTO',
       'FORMULACION Y GESTION DE PROYECTOS', 'FOTOGRAMETRIA 1',
       'FOTOGRAMETRIA 2', 'FOTOGRAMETRIA DIGITAL', 'FOTOGRAMETRIA I',
       'FOTONICA APLICADA', 'FUNDAMENTO DE LA MECANICA NAVAL',
       'FUNDAMENTOS DE ELECTRONICA INDUSTRIAL',
       'FUNDAMENTOS DE MEDIO DE RED', 'FUNDAMENTOS DE PLANTA EXTERNA',
       'FUNDAMENTOS MATEMATICOS PARA LA CIENCIAS GEOGRAFICAS',
       'GEODESIA GEOMETRICA', 'GEODESIA GRAVIMETRICA',
       'GEODESIA SATELITAL', 'GEOGRAFIA HUMANA', 'GEOGRAFIA TURISTICA',
       'GEOLOGIA DEL PARAGUAY', 'GEOLOGIA GENERAL', 'GEOMETRIA ANALITICA',
       'GEOMETRIA DESCRIPTIVA', 'GEOMORFOLOGIA', 'GEOTECNIA 1',
       'GEOTECNIA 2', 'GEST. DE CALIDAD E IMPACTO AMBIENTAL',
       'GESTION DE CALIDAD', 'GESTION DE LA CALIDAD Y MEDIO AMBIENTE',
       'GESTION DE PROYECTOS', 'GESTION DE SALUD Y SEGURIDAD INDUST.',
       'GESTION EMPRESARIAL', 'GESTION INTEGRAL DE RESIDUOS',
       'GESTION Y CONSERVACION DE RECURSOS NATURALES', 'HIDRAULICA 1',
       'HIDRAULICA 2', 'HIDROGEOLOGIA', 'HIDROLOGIA 2',
       'HIDROLOGIA GENERAL  E HIDRAULICA',
       'HIDROLOGIA GENERAL E HIDRAULICA', 'HIDROTECNIA 1',
       'HIDROTECNIA 2', 'HIGIENE Y SEGURIDAD INDUSTRIAL',
       'HORMIGON ARMADO 1', 'HORMIGON ARMADO 2', 'HORMIGON PRETENSADO',
       'IMPACTO AMBIENTAL EN OBRAS VIALES', 'INFORMATICA',
       'INFORMATICA 2', 'INFRAESTRUCTURA DE DATOS ESPECIALES',
       'INGENIERIA DE CONFIABILIDAD Y MANTENIMIENTO',
       'INGENIERIA DE MANTENIMIENTO', 'INGENIERIA DEL TRAFICO',
       'INGENIERIA ECONOMICA', 'INGLES TECNICO', 'INMOTICA Y DOMOTICA',
       'INNOVACION Y EMPRENDIMIENTO',
       'INSTALACION Y EQUIPAMIENTO DE EDIFICIOS',
       'INSTALACIONES  ELECTRICAS', 'INSTALACIONES  INDUSTRIALES',
       'INSTALACIONES ELECTRICAS', 'INSTALACIONES ELECTRICAS ESPECIALES',
       'INSTALACIONES INDUSTRIALES',
       'INSTALACIONES Y EQUIPOS DE EDIFICIOS',
       'INSTR. PARA CONTROL Y AUTOM.', 'INSTRUMENTACION PARA TELEC.',
       'INSTRUMENTACION PARA TELECOMUNICACIONES',
       'INSTRUMENTACION Y AUTOMATIZACION',
       'INSTRUMENTACION Y MEDICIONES ELECTRICAS',
       'INSTRUMENTACIÓN Y AUTOMATIZACION',
       'INSTRUMENTOS PARA CONTROL Y AUTOMATIZACION',
       'INT. A LA PROGRAMACION DE CNC', 'INTELIGENCIA ARTIFICIAL',
       'INTERPRETACION DE IMAGENES RADAR',
       'INTR AL DESARROLLO TERRITORIAL- MANEJO DE CONSERVACION DE SU',
       'INTR. AL PROYECTO Y DISEÑO DE TORRES DE TELECOMUNICACION',
       'INTROD. A LA INGENIERIA NAVAL',
       'INTRODUCCION  A LA INVESTIGACION',
       'INTRODUCCION A ELECTRONICA MEDICA',
       'INTRODUCCION A LA CIENCIA AMBIENTAL',
       'INTRODUCCION A LA ELECTRONICA MEDICA',
       'INTRODUCCION A LA ENERGIA EOLICA',
       'INTRODUCCION A LA ENERGIA FOTOVOLTAICA',
       'INTRODUCCION A LA FISICA ATOMICA Y MOLECULAR',
       'INTRODUCCION A LA GESTION DE ACTIVOS',
       'INTRODUCCION A LA INVESTIGACION', 'INTRODUCCION A LA MINERIA',
       'INTRODUCCION A LA SIMULACION',
       'INTRODUCCION AL ORDENAMIENTO TERRITORIAL',
       'INVEST. DE OPERACIONES 2', 'INVEST. DE OPERACIONES 3',
       'INVESTIGACION DE OPERACIONES 1', 'INVESTIGACION DE OPERACIONES 2',
       'INVESTIGACION DE OPERACIONES 3', 'INVESTIGACION OPERATIVA',
       'LABORATORIO DE REDES', 'LABORATORIO MECANICO 1',
       'LABORATORIO MECANICO 2', 'LABORATORIO MECANICO 3',
       'LABORATORIO VIAL', 'LEAN PRODUCTION', 'LEGISLACION',
       'LENGUAJE DE PROGRAMACION', 'LENGUAJE DE PROGRAMACION VISUAL',
       'LEVANT. REG., CATASTRALES E HIDROTOPOGRAFICOS',
       'LEVANTAMIENTO REGIONALES Y CATASTRALES', 'LOGISTICA',
       'LT PARA TELECOMUNICACIONES', 'MANTENIMIENTO DE CAMINOS',
       'MANTENIMIENTO INDUSTRIAL', 'MANTENIMIENTO MECANICO',
       'MAQUINAS  ELECTRICAS  1', 'MAQUINAS  TERMICAS  2',
       'MAQUINAS DE FLUJO', 'MAQUINAS ELECTRICAS',
       'MAQUINAS ELECTRICAS 1', 'MAQUINAS ELECTRICAS 2',
       'MAQUINAS HIDRAULICAS', 'MAQUINAS TERMICAS  1',
       'MAQUINAS TERMICAS 1', 'MAQUINAS TERMICAS 2',
       'MAQUINAS Y EQUIPOS PARA LA CONSTRUCCION', 'MATERIALES 1',
       'MATERIALES 2', 'MATERIALES DE INGENIERIA',
       'MATERIALES DE OBRAS CIVILES', 'MATERIALES DE OBRAS CIVILES 1',
       'MATERIALES DE OBRAS CIVILES 2', 'MECANICA DE FLUIDOS',
       'MECANICA DE FLUIDOS AVANZADOS', 'MECANICA DE MATERIALES 1',
       'MECANICA DE MATERIALES 2', 'MECANICA DE SOLIDOS',
       'MECANICA DE SUELO Y ROCA', 'MECANISMOS',
       'MECANIZADO CONVENCIONAL', 'MEDICION E INSTRUMENTACION',
       'MEDICIONES E INSTRUMENTACION', 'MERCADOS ELECTRICOS',
       'METEOROLOGIA Y CLIMATOLOGIA', 'METODOLOGIA DE INVESTIGACION',
       'METODOLOGIA DE LA INVESTIGACION', 'METODOS NUMERICOS',
       'METROLOGIA', 'MICROCONTROLADORES', 'MICROELECTRONICA',
       'MICROONDAS',
       'MODELACION COMPUTACIONAL DE ESTRUCTURAS-METODO ELEM. FINITO',
       'MONITOREO AMBIENTAL', 'MOTORES Y COMPONENTES AUTOM.',
       'NOCIONES DE DERECHO', 'OBRAS FLUVIALES',
       'OPERACIONES INDUSTRIALES', 'ORGANIZACION DE EMPRESAS',
       'ORGANIZACION DE EMPRESAS 1', 'ORGANIZACION DE EMPRESAS 2',
       'ORGANIZACION INDUSTRIAL',
       'ORGANIZACION INDUSTRIAL Y SEGURIDAD DEL TRABAJO', 'PASANTIA',
       'PASANTIAS', 'PATOLOGIA Y TERAPIA DE LAS CONSTRUCCIONES',
       'PLANEAMIENTO Y CONTROL DE PRODUCCION',
       'PLANIF. Y CONTROL DE LA PRODUCCION',
       'PLANIFICACION DE SISTEMAS ELECTRICOS',
       'PLANIFICACION DEL USO DE LA TIERRA',
       'PLANIFICACION ESTRATEGICA PARA EL PROYECTO TERRITORIAL',
       'PLANIFICACION ESTRATEGICA PARA LOS PROYECTOS AMBIENTALES',
       'PLANIFICACION Y GESTIÓN DE REDES', 'PLASTICOS', 'PLASTICOS I',
       'PLC', 'POLITICA Y LEGISLACION PROFESIONAL',
       'PRINCIPIOS DE ECONOMIA', 'PROBABILIDAD Y ESTADISTICA',
       'PROC. DIGITALES DE SEÑALES',
       'PROCEDIMIENTO DE EVALUACION DE IMPACTO AMBIENTAL',
       'PROCESAMIENTO DIGITAL DE IMAGENES',
       'PROCESAMIENTO DIGITAL DE SEÑALES',
       'PROCESAMIENTO ELECTRONICO DE DATOS 1',
       'PROCESAMIENTO ELECTRONICO DE DATOS 2',
       'PROCESAMIENTO ELECTRONICO DE DATOS 3', 'PROCESOS DE FABRICACION',
       'PROCESOS DE FABRICACION 1', 'PROCESOS DE FABRICACION 2',
       'PROCESOS DE SOLDADURA', 'PROCESOS INDUSTRIALES 1',
       'PROCESOS INDUSTRIALES II', 'PROGRAMACION ORIENTADA A OBJETOS',
       'PROGRAMACION Y CONTROL DE OBRA',
       'PROGRAMACION Y CONTROL DE OBRAS', 'PROPAGACION',
       'PROPAGACION Y ANTENAS', 'PROTECCIONES ELECTRICAS DE POTENCIA',
       'PROTOCOLO DE COMUNICACION', 'PROTOCOLOS DE COMUNICACION',
       'PROYECTO', 'PROYECTO 1', 'PROYECTO 2', 'PROYECTO 3', 'PROYECTO 4',
       'PROYECTO INTEGRADO', 'PROYECTO Y DISEÑO',
       'PROYECTOS ESTRUCTURALES', 'PUENTES', 'PUERTOS', 'QUIMICA GENERAL',
       'RECUBRIMIENTO METALICO POR GALVANIZADO',
       'REDES DE SENSORES INALAMBRICOS', 'REDES INDUSTRIALES',
       'REDES INDUSTRIALES Y SCADA',
       'REGIMEN JURIDICO, TEORICO Y PRACTICO DEL INMUEBLE',
       'RESISTENCIA DE MATERIALES', 'ROBOTICA 1', 'ROBOTICA 2',
       'SANEAMIENTO Y MEDIO AMBIENTE', 'SANEAMIENTO Y MEDIO AMBIENTE 1',
       'SANEAMIENTO Y MEDIO AMBIENTE 2', 'SEGURIDAD EN EL TRABAJO',
       'SEGURIDAD EN OBRAS', 'SENSORES REMOTOS', 'SENSORES REMOTOS 1',
       'SENSORES REMOTOS 2', 'SEÑALES Y SISTEMAS',
       'SIG ANALISIS ESPACIAL', 'SIG APLICADO AL AMBIENTE',
       'SIMULACION DE SISTEMAS PRODUCTIVOS',
       'SIMULACION HIDROLOGICA E HIDRAULICA',
       'SIST. DE COMUNICACIONES CELULARES 2',
       'SIST. DE CONTROL AUTOMATICO 2',
       'SIST.DE COMUNICACIONES CELULARES 1', 'SISTEMA AMBIENTAL',
       'SISTEMA DE CALIDAD', 'SISTEMA DE CONTROL',
       'SISTEMA DE CONTROL  AUTOMATICO  1',
       'SISTEMA DE CONTROL AUTOMATICO 1',
       'SISTEMA DE INFORMACION GEOGRAFICA', 'SISTEMA DE MODULACION 1',
       'SISTEMA DE MODULACION 2', 'SISTEMA DE PLANIF. ESTRATEGICA',
       'SISTEMA DE PLANIFICACION ESTRATEGICA', 'SISTEMA DE REDES 1',
       'SISTEMA DE REFRIGERACION APLICADOS', 'SISTEMA DE TELEVISION 1',
       'SISTEMAS DE COMUNICACIONES 1', 'SISTEMAS DE COMUNICACIONES 2',
       'SISTEMAS DE CONTROL', 'SISTEMAS DE CONTROL AUTOMATICO 1',
       'SISTEMAS DE CONTROL AUTOMATICO 2',
       'SISTEMAS DE CONTROL AUTOMATICO II', 'SISTEMAS DE CONTROL DIGITAL',
       'SISTEMAS DE MODULACION 1', 'SISTEMAS DE MODULACION 2',
       'SISTEMAS DE REDES 2', 'SISTEMAS DE TELEFONIA 1',
       'SISTEMAS DE TELEFONIA 2', 'SISTEMAS DE TELEVISION',
       'SISTEMAS DIGITALES 1', 'SISTEMAS DIGITALES 2',
       'SISTEMAS DISTRIBUIDOS', 'SISTEMAS HIDRAULICOS Y NEUMATICOS',
       'SISTEMAS OPERATIVOS', 'SOCIOLOGIA', 'SOLDADURAS',
       'SUBESTACIONES ELECTRICAS', 'TALLER DE PRACTICA PROFESIONAL',
       'TALLER DE PRACTICA PROFESIONAL EN GESTION',
       'TECNICA DE ENERGIAS ALTERNATIVAS', 'TECNOLOGIA  MECANICA  1',
       'TECNOLOGIA  MECANICA  2', 'TECNOLOGIA DE ENERGIA ALTERNATIVAS',
       'TECNOLOGIA DE LA INFORMACION', 'TECNOLOGIA DE LOS MATERIALES',
       'TECNOLOGIA DEL HORMIGON', 'TECNOLOGIA MECANICA',
       'TECNOLOGIA MECANICA 1', 'TECNOLOGIA MECANICA 2', 'TELEFONIA 1',
       'TELEFONIA 2', 'TELEMETRIA Y TELECONTROL', 'TELEVISION SOBRE IP',
       'TEORIA DE CIRCUITOS', 'TEORIA DE CIRCUITOS 1',
       'TEORIA DE CIRCUITOS 2', 'TEORIA DE CIRCUITOS 3', 'TERMODINAMICA',
       'TERMOTECNIA', 'TERMOTECNIA 1', 'TERMOTECNIA 2',
       'TERRITORIO Y POBLACION', 'TOPOGRAFIA', 'TOPOGRAFIA 1',
       'TOPOGRAFIA 2', 'TOPOGRAFIA DE OBRA', 'TOPOGRAFIA I',
       'TRACTORES Y MAQUINARIAS', 'TRANSFERENCIA DE CALOR',
       'TRANSITORIOS', 'TRANSMISION DE ENERGIA  ELECTRICA',
       'TRANSMISION DE ENERGIA ELECTRICA', 'TRATAMIENTO DE AGUAS',
       'TRATAMIENTO DE EFLUENTES', 'VIAS DE COMUNICACION',
       'VIAS DE COMUNICACION 1', 'VIAS DE COMUNICACION 2',
       'VIAS DE COMUNICACION 3', 'VIBRACIONES MECANICAS'], dtype=object)

Hola mundo

In [7]:
carrera=pd.DataFrame(columns=lectura.columns)
for car in ['MCT-175-09', 'MCT-PLS09 ','MCT-PLS13 ', 'MCT9-OPT  ']:
     carrera=pd.concat([carrera, lectura[lectura["Cod.Car.Sec"]==car]], axis=0)

In [8]:
np.unique(carrera["Cod.Car.Sec"])

array(['MCT-175-09', 'MCT-PLS09 ', 'MCT-PLS13 ', 'MCT9-OPT  '],
      dtype=object)

In [9]:
estudiantes=np.unique(carrera.id_anony.values)

In [10]:
len(estudiantes)

922

In [18]:
NuevosDatos=pd.DataFrame(columns=["id","AnhoIni","cicloIni","AnhoFin","cicloFin"])
for ides in estudiantes:
    registro=carrera[carrera.id_anony.values==ides]
    if(np.sum(registro["Cod.Curso"].values==1)>=1 and np.sum(registro["Cod.Curso"].values==4)>=1):
        if()
            break

In [19]:
registro

,Unnamed: 0,danho,ciclo,Cod.Asign,Asignatura,Cod.Car.Sec,Cod.Curso,Convocatoria,Anho,Semestre,...,Segundo.Par,AOT,Primer.Rec,Segundo.Rec,Nota.Final,Tercer.Par,Asis,Cuarto.Par,4P_60,id_anony
5510,5510,2012,1,9005,CALCULO 2,MCT-PLS09,2,1,2012,1,...,23,5,22,0,2F-2,0.0,1.0,NaN,NaN,es_1318
5961,5961,2012,1,9006,FISICA 2,MCT-PLS09,2,1,2012,1,...,11,6,0,0,NaN,0.0,1.0,NaN,NaN,es_1318
6339,6339,2012,1,9007,ALGEBRA LINEAL 2,MCT-PLS09,2,1,2012,1,...,6,3,26,0,3F-3,0.0,1.0,NaN,NaN,es_1318
6732,6732,2012,1,9008,QUIMICA GENERAL,MCT-PLS09,2,1,2012,1,...,0,4,0,0,NaN,0.0,1.0,NaN,NaN,es_1318
7034,7034,2012,1,9009,DIBUJO TECNICO,MCT-PLS09,2,1,2012,1,...,0,2,0,0,NaN,0.0,0.0,NaN,NaN,es_1318
7375,7375,2012,1,9010,COMPUTACION,MCT-PLS09,2,1,2012,1,...,17,5,30,0,NaN,0.0,1.0,NaN,NaN,es_1318
121440,11349,2017,2,5012,CALCULO 3,MCT-PLS09,3,1,2017,2,...,14,6,0,0,3F-1,0.0,1.0,NaN,NaN,es_1318
121539,11448,2017,2,5014,ESTATICA,MCT-PLS09,3,1,2017,2,...,0,2,0,0,NaN,0.0,0.0,NaN,NaN,es_1318
133672,10184,2018,1,5012,CALCULO 3,MCT-PLS09,3,1,2018,1,...,10,0,0,0,1F-3,0.0,0.0,NaN,NaN,es_1318
134931,11443,2018,1,5405,FISICA DE SEMICONDUCTORES,MCT-PLS09,4,1,2018,1,...,13,9,10,0,NaN,0.0,1.0,NaN,NaN,es_1318
135049,11561,2018,1,5442,METODOS NUMERICOS,MCT-PLS09,4,1,2018,1,...,0,2,0,0,NaN,0.0,1.0,NaN,NaN,es_1318
135508,12020,2018,1,9008,QUIMICA GENERAL,MCT-PLS09,2,1,2018,1,...,0,0,0,0,NaN,0.0,1.0,NaN,NaN,es_1318
113088,2997,2017,2,13006,GEOMETRIA DESCRIPTIVA,MCT-PLS13,1,1,2017,2,...,0,4,0,0,NaN,0.0,1.0,NaN,NaN,es_1318
125368,1880,2018,1,13010,QUIMICA GENERAL,MCT-PLS13,2,1,2018,1,...,0,2,0,0,NaN,0.0,0.0,NaN,NaN,es_1318
131764,8276,2018,1,13704,TEORIA DE CIRCUITOS,MCT-PLS13,4,1,2018,1,...,15,8,0,24,NaN,0.0,1.0,NaN,NaN,es_1318
131832,8344,2018,1,13705,PROGRAMACION ORIENTADA A OBJETOS,MCT-PLS13,4,1,2018,1,...,8,5,0,0,NaN,0.0,1.0,NaN,NaN,es_1318
166177,2389,2019,2,13006,GEOMETRIA DESCRIPTIVA,MCT-PLS13,1,2,2019,2,...,9,6,0,0,NaN,0.0,1.0,NaN,NaN,es_1318
167944,4156,2019,2,13010,QUIMICA GENERAL,MCT-PLS13,2,2,2019,2,...,13,5,20,0,NaN,0.0,1.0,NaN,NaN,es_1318
169922,6134,2019,2,13015,ESTATICA,MCT-PLS13,3,2,2019,2,...,0,0,0,0,NaN,0.0,1.0,NaN,NaN,es_1318
176304,12516,2019,2,13706,SEÑALES Y SISTEMAS,MCT-PLS13,5,1,2019,2,...,19,8,0,0,"1F-1,3F-2",0.0,1.0,NaN,NaN,es_1318
176349,12561,2019,2,13707,ELECTRONICA 1,MCT-PLS13,5,1,2019,2,...,20,8,19,27,NaN,0.0,1.0,NaN,NaN,es_1318
176392,12604,2019,2,13708,TERMODINAMICA,MCT-PLS13,5,1,2019,2,...,11,5,24,10,NaN,0.0,1.0,NaN,NaN,es_1318
178747,14959,2019,2,5738,INTELIGENCIA ARTIFICIAL,MCT9-OPT,13,2,2019,2,...,0,2,0,0,NaN,0.0,0.0,NaN,NaN,es_1318

In [48]:
flagPasaron=np.logical_and(carrera.Asignatura.values=="CALCULO 1", carrera["Aprobado"]=="S")
carreraP=carrera[flagPasaron]

In [49]:
carreraP.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 349 entries, 13940 to 193704
Data columns (total 23 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    349 non-null    object
 1   danho         349 non-null    object
 2   ciclo         349 non-null    object
 3   Cod.Asign     349 non-null    object
 4   Asignatura    349 non-null    object
 5   Cod.Car.Sec   349 non-null    object
 6   Cod.Curso     349 non-null    object
 7   Convocatoria  349 non-null    object
 8   Anho          349 non-null    object
 9   Semestre      349 non-null    object
 10  Aprobado      349 non-null    object
 11  Anho.Firma    349 non-null    object
 12  Primer.Par    349 non-null    object
 13  Segundo.Par   349 non-null    object
 14  AOT           349 non-null    object
 15  Primer.Rec    349 non-null    object
 16  Segundo.Rec   349 non-null    object
 17  Nota.Final    349 non-null    object
 18  Tercer.Par    349 non-null    float64
 19  Asis          349 non-null    float64
 20  Cuarto.Par    37 non-null     float64
 21  4P_60         37 non-null     float64
 22  id_anony      349 non-null    object
dtypes: float64(4), object(19)
memory usage: 65.4+ KB

In [50]:
flagFirma2011=carreraP["Anho.Firma"]==2011

carreraPL=carreraP[~flagFirma2011]

In [51]:
carreraPL.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 348 entries, 13940 to 193704
Data columns (total 23 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    348 non-null    object
 1   danho         348 non-null    object
 2   ciclo         348 non-null    object
 3   Cod.Asign     348 non-null    object
 4   Asignatura    348 non-null    object
 5   Cod.Car.Sec   348 non-null    object
 6   Cod.Curso     348 non-null    object
 7   Convocatoria  348 non-null    object
 8   Anho          348 non-null    object
 9   Semestre      348 non-null    object
 10  Aprobado      348 non-null    object
 11  Anho.Firma    348 non-null    object
 12  Primer.Par    348 non-null    object
 13  Segundo.Par   348 non-null    object
 14  AOT           348 non-null    object
 15  Primer.Rec    348 non-null    object
 16  Segundo.Rec   348 non-null    object
 17  Nota.Final    348 non-null    object
 18  Tercer.Par    348 non-null    float64
 19  Asis          348 non-null    float64
 20  Cuarto.Par    37 non-null     float64
 21  4P_60         37 non-null     float64
 22  id_anony      348 non-null    object
dtypes: float64(4), object(19)
memory usage: 65.2+ KB

In [53]:
flagNoPasaron=np.logical_and(carrera.Asignatura.values=="CALCULO 1",carrera["Aprobado"]=="N")
carreraNP=carrera[flagNoPasaron]
carreraNP.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 425 entries, 13943 to 207709
Data columns (total 23 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    425 non-null    object
 1   danho         425 non-null    object
 2   ciclo         425 non-null    object
 3   Cod.Asign     425 non-null    object
 4   Asignatura    425 non-null    object
 5   Cod.Car.Sec   425 non-null    object
 6   Cod.Curso     425 non-null    object
 7   Convocatoria  425 non-null    object
 8   Anho          425 non-null    object
 9   Semestre      425 non-null    object
 10  Aprobado      425 non-null    object
 11  Anho.Firma    425 non-null    object
 12  Primer.Par    425 non-null    object
 13  Segundo.Par   425 non-null    object
 14  AOT           425 non-null    object
 15  Primer.Rec    425 non-null    object
 16  Segundo.Rec   425 non-null    object
 17  Nota.Final    96 non-null     object
 18  Tercer.Par    425 non-null    float64
 19  Asis          425 non-null    float64
 20  Cuarto.Par    95 non-null     float64
 21  4P_60         95 non-null     float64
 22  id_anony      425 non-null    object
dtypes: float64(4), object(19)
memory usage: 79.7+ KB

In [54]:
carreraNP.head()

,Unnamed: 0,danho,ciclo,Cod.Asign,Asignatura,Cod.Car.Sec,Cod.Curso,Convocatoria,Anho,Semestre,...,Segundo.Par,AOT,Primer.Rec,Segundo.Rec,Nota.Final,Tercer.Par,Asis,Cuarto.Par,4P_60,id_anony
13943,6503,2012,2,9001,CALCULO 1,MCT-PLS09,1,1,2012,2,...,6,1,0,0,NaN,0.0,1.0,NaN,NaN,es_2833
13950,6510,2012,2,9001,CALCULO 1,MCT-PLS09,1,1,2012,2,...,6,3,0,0,NaN,0.0,1.0,NaN,NaN,es_2838
13960,6520,2012,2,9001,CALCULO 1,MCT-PLS09,1,1,2012,2,...,18,4,0,0,"1F-1,2F-1",0.0,1.0,NaN,NaN,es_2845
14051,6611,2012,2,9001,CALCULO 1,MCT-PLS09,1,1,2012,2,...,7,2,0,0,NaN,0.0,1.0,NaN,NaN,es_2922
14078,6638,2012,2,9001,CALCULO 1,MCT-PLS09,1,1,2012,2,...,19,2,0,0,NaN,0.0,1.0,NaN,NaN,es_2944

In [58]:
carreraPLN=pd.merge(carreraPL, carreraNP, on=['id_anony'], how='right')

In [61]:
carreraPLN.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 427 entries, 0 to 426
Data columns (total 45 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0_x    72 non-null     object
 1   danho_x         72 non-null     object
 2   ciclo_x         72 non-null     object
 3   Cod.Asign_x     72 non-null     object
 4   Asignatura_x    72 non-null     object
 5   Cod.Car.Sec_x   72 non-null     object
 6   Cod.Curso_x     72 non-null     object
 7   Convocatoria_x  72 non-null     object
 8   Anho_x          72 non-null     object
 9   Semestre_x      72 non-null     object
 10  Aprobado_x      72 non-null     object
 11  Anho.Firma_x    72 non-null     object
 12  Primer.Par_x    72 non-null     object
 13  Segundo.Par_x   72 non-null     object
 14  AOT_x           72 non-null     object
 15  Primer.Rec_x    72 non-null     object
 16  Segundo.Rec_x   72 non-null     object
 17  Nota.Final_x    72 non-null     object
 18  Tercer.Par_x    72 non-null     float64
 19  Asis_x          72 non-null     float64
 20  Cuarto.Par_x    22 non-null     float64
 21  4P_60_x         22 non-null     float64
 22  id_anony        427 non-null    object
 23  Unnamed: 0_y    427 non-null    object
 24  danho_y         427 non-null    object
 25  ciclo_y         427 non-null    object
 26  Cod.Asign_y     427 non-null    object
 27  Asignatura_y    427 non-null    object
 28  Cod.Car.Sec_y   427 non-null    object
 29  Cod.Curso_y     427 non-null    object
 30  Convocatoria_y  427 non-null    object
 31  Anho_y          427 non-null    object
 32  Semestre_y      427 non-null    object
 33  Aprobado_y      427 non-null    object
 34  Anho.Firma_y    427 non-null    object
 35  Primer.Par_y    427 non-null    object
 36  Segundo.Par_y   427 non-null    object
 37  AOT_y           427 non-null    object
 38  Primer.Rec_y    427 non-null    object
 39  Segundo.Rec_y   427 non-null    object
 40  Nota.Final_y    97 non-null     object
 41  Tercer.Par_y    427 non-null    float64
 42  Asis_y          427 non-null    float64
 43  Cuarto.Par_y    95 non-null     float64
 44  4P_60_y         95 non-null     float64
dtypes: float64(8), object(37)
memory usage: 153.5+ KB

In [64]:
carreraPLN[["Aprobado_x","Aprobado_y"]].values[0:10]

array([[nan, 'N'],
       ['S', 'N'],
       ['S', 'N'],
       [nan, 'N'],
       [nan, 'N'],
       [nan, 'N'],
       ['S', 'N'],
       ['S', 'N'],
       ['S', 'N'],
       ['S', 'N']], dtype=object)

In [18]:
for asig in asignaturas:
    flag=lectura.Asignatura.values==asig
    print(np.sum(lectura["Aprobado"][flag]=="S"))

2633
2519
2495